apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name }}-deployment
spec:
  selector:
    matchLabels:
      app: fn-webserver
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fn-webserver
    spec:
      containers:
        - image: {{ .Values.image }}
          name: fn-webserver
          ports:
            - containerPort: {{ .Values.service.port }}