apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}-service-cluster-ip
  labels:
    app: fn-webserver
spec:
  type: ClusterIP
  selector:
    app: fn-webserver
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
