apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name }}-deployment
spec:
  selector:
    matchLabels:
      app: fn-webadmin
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fn-webadmin
    spec:
      containers:
        - image: {{ .Values.image }}
          name: fn-webadmin
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: REACT_APP_WEB_SERVER_URL
              value: {{ .Values.application.webserverUrl }}
